config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root "todos#index"
  resources :todos do
    member do
      patch 'status'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :todos

  validates :name, presence: true
  validates :description, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :category

  validates :title, presence: true
  validates :status, presence: true
  validates :priority, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 5
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @todos = @category.todos.order('priority desc').page params[:page]
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :status, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.where(status: 0).order('priority desc').page params[:page]
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def status
    @todo.status = params[:status]
    @todo.save!
    redirect_to root_url, notice: "「#{@todo.title}」が完了しました。"
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :body, :priority, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>

  <%= render 'shared/errors', object: category %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category %></td>
        <td><%= category.description %></td>
        <td></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<%= render 'todos/todos_table', todos: @todos %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railstodo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1><%= link_to '俺のToDoアプリケーション', root_url %></h1>
    <div id="wrapper">
      <header>
        <%= link_to '新しいTodo', new_todo_path %>
        <%= link_to 'カテゴリ', categories_path %>
        <%= link_to '新しいカテゴリ', new_category_path %>
      </header>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "個") %> エラーがあります:</h2>

    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>

  <%= render 'shared/errors', object: todo %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <% @categories = Category.all %>
    <%= form.select :category_id, @categories.map{|t| [t.name, t.id]}, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_todos_table.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% todos.each do |todo| %>
      <tr>
        <td><%= link_to todo.title, todo %></td>
        <td><%= todo.body %></td>
        <td><%= todo.status %></td>
        <td><%= todo.priority %></td>
        <td><%= todo.category&.name %></td>
        <td><%= link_to '完了', status_todo_path(todo, status: 1), method: :patch %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate todos %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Todo一覧</h1>

<%= render 'todos_table', todos: @todos %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @todo.body %>
</p>

<p>
  <strong>Status:</strong>
  <%= @todo.status %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @todo.priority %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>